
name = "DashpoolComponents"
uuid = "1b08a953-4be3-4667-9a23-6f785c13abf9"
authors = ["Viktor Kr√ºckl <viktor@krueckl.de>"]
version = "0.0.92"

[deps]
Dash = "1b08a953-4be3-4667-9a23-3db579824955"

[compat]
julia = "1.2"
Dash = "0.1.3, 1.0"
